(move) Move the dev pipeline / standard-container
This patchset copies the development-pipeline and standard-container
into the sample network mongodb directory to begin testing the pipeline
and standard-container in a namespace created by jarvis-system.

Change-Id: I8448a122e8da218752ea57b15fb2983881e90ec9

diff --git a/charts/jarvis-system/templates/Task-createProjectAccess.yaml b/charts/jarvis-system/templates/Task-createProjectAccess.yaml
--- a/charts/jarvis-system/templates/Task-createProjectAccess.yaml
+++ b/charts/jarvis-system/templates/Task-createProjectAccess.yaml
@@ -21,29 +21,38 @@ spec:
       image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "task_create_namespace" ) }}
       script: |
         #!/bin/bash
+        set -ex
         create_namespace() {
           if ! [[ $(kubectl get ns jarvis-$(params.changeNumber)-$(params.patchSetNumber)) ]] ; then
             kubectl create ns jarvis-$(params.changeNumber)-$(params.patchSetNumber)
             echo "Created namespace jarvis-$(params.changeNumber)-$(params.patchSetNumber)"
           else
-            echo "Namespace already exists"
-            exit
+            echo "Namespace already exists, delete all resources for re-run."
+            kubectl delete all --all -n jarvis-$(params.changeNumber)-$(params.patchSetNumber)
           fi
         }
         create_namespace
     - name: create-k8s-objects
       image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "task_create_namespace" ) }}
       script: |
-        #Service account creation
-        cat > $(workspaces.output.path)/service-account.yaml <<EOF
+        #!/bin/bash
+        create_sa() {
+          if ! [[ $(kubectl get serviceaccount -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) sa-development-pipeline) ]] ; then
+            tee $(workspaces.output.path)/service-account.yaml <<EOF
         apiVersion: v1
         kind: ServiceAccount
         metadata:
-          name: jarvis-$(params.changeNumber)-$(params.patchSetNumber)
+          name: sa-development-pipeline
           namespace: jarvis-$(params.changeNumber)-$(params.patchSetNumber)
         EOF
-        #Role creation
-        cat > $(workspaces.output.path)/role.yaml <<EOF
+          else
+            echo "Service Account already exists"
+            exit
+          fi
+        }
+        create_role() {
+          if ! [[ $(kubectl get role -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) jarvis-$(params.changeNumber)-$(params.patchSetNumber)) ]] ; then
+            tee $(workspaces.output.path)/role.yaml <<EOF
         apiVersion: rbac.authorization.k8s.io/v1
         kind: Role
         metadata:
@@ -68,8 +77,14 @@ spec:
             resources: ["roles", "rolebindings"]
             verbs: ["get"]
         EOF
-        #Rolebinding creation
-        cat > $(workspaces.output.path)/rolebinding.yaml <<EOF
+          else
+            echo "Role already exists"
+            exit
+          fi
+        }
+        create_rolebinding() {
+          if ! [[ $(kubectl get rolebinding -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) jarvis-$(params.changeNumber)-$(params.patchSetNumber)) ]] ; then
+            tee $(workspaces.output.path)/rolebinding.yaml <<EOF
         apiVersion: rbac.authorization.k8s.io/v1
         kind: RoleBinding
         metadata:
@@ -77,13 +92,22 @@ spec:
           namespace: jarvis-$(params.changeNumber)-$(params.patchSetNumber)
         subjects:
           - kind: ServiceAccount
-            name: jarvis-$(params.changeNumber)-$(params.patchSetNumber)
+            name: sa-development-pipeline
         roleRef:
           apiGroup: rbac.authorization.k8s.io
           kind: Role
           name: jarvis-$(params.changeNumber)-$(params.patchSetNumber)
         EOF
-        #!/bin/bash
+          else
+            echo "rolebinding already exists"
+            exit
+          fi
+        }
+        #Service account creation
+        create_sa
+        create_role
+        create_rolebinding
+
         cat $(workspaces.output.path)/service-account.yaml | kubectl apply -f -
         cat $(workspaces.output.path)/role.yaml | kubectl apply -f -
         cat $(workspaces.output.path)/rolebinding.yaml | kubectl apply -f -
@@ -138,13 +162,82 @@ spec:
     - name: create-secrets
       image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "task_secrets" ) }}
       script: |
-        #!/bin/sh
+        #!/bin/bash
+        ## Creating kubeconfig secret in correct namespace
+        SECRET_JSON_ORIGINAL=$(mktemp --suffix=".json")
+        kubectl get secret -n development-pipeline kubeconfig-secret -o=json > "$SECRET_JSON_ORIGINAL"
+        SECRET_JSON=$(mktemp --suffix=".json")
+        jq 'del(.metadata.namespace) | del(.metadata.creationTimestamp) | del(.metadata.labels."controller-uid") | del(.metadata.resourceVersion) | del(.metadata.selfLink) | del(.metadata.uid) | del(.spec.selector) | del(.spec.template.metadata.creationTimestamp) | del(.spec.template.metadata.labels."controller-uid" )' "$SECRET_JSON_ORIGINAL" > "$SECRET_JSON"
 
-        kubectl create secret generic harbor-ca --from-file=harbor-ca=/etc/jarvis/certs/ca/ca.pem -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) || true
-        kubectl create secret generic kubeconfig-secret --from-file=kubeconfig=$HOME/.kube/config -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) || true
-        #Required to know what authentication to use when pushing to Harbor, should have a different ID then admin in future.
-        kubectl create secret generic harbor-basic-auth --from-literal=username='admin' --from-literal=password='Harbor12345' -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) || true
-        kubectl create secret docker-registry harbor-docker-auth --docker-username=admin --docker-password=Harbor12345 --docker-email=example@gmail.com --docker-server=harbor-core.jarvis.local -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) || true
+        cat "$SECRET_JSON" | kubectl create -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) -f -
+
+        ## Creating Harbor certificate in correct namespace
+        SECRET_JSON_ORIGINAL=$(mktemp --suffix=".json")
+        kubectl get secret -n development-pipeline harbor-ca -o=json > "$SECRET_JSON_ORIGINAL"
+        SECRET_JSON=$(mktemp --suffix=".json")
+        jq 'del(.metadata.namespace) | del(.metadata.creationTimestamp) | del(.metadata.labels."controller-uid") | del(.metadata.resourceVersion) | del(.metadata.selfLink) | del(.metadata.uid) | del(.spec.selector) | del(.spec.template.metadata.creationTimestamp) | del(.spec.template.metadata.labels."controller-uid" )' "$SECRET_JSON_ORIGINAL" > "$SECRET_JSON"
+
+        cat "$SECRET_JSON" | kubectl create -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) -f -
+
+        rm "$SECRET_JSON_ORIGINAL"
+        rm "$SECRET_JSON"
+
+        ## Harbor basic auth and docker auth
+        kubectl create secret generic harbor-basic-auth \
+          --from-literal=username='admin' \
+          --from-literal=password='Harbor12345' \
+          -n jarvis-$(params.changeNumber)-$(params.patchSetNumber)
+
+        kubectl create secret docker-registry harbor-docker-auth \
+          --docker-username=admin \
+          --docker-password=Harbor12345 \
+          --docker-email=example@gmail.com \
+          --docker-server=harbor-core.jarvis.local \
+          -n jarvis-$(params.changeNumber)-$(params.patchSetNumber)
+    - name: install-development-pipeline
+      image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "task_secrets" ) }}
+      script: |
+        #!/bin/bash
+
+        change_ref="refs/changes/$(echo "0$(params.changeNumber)" | awk '{ print substr( $0, length($0) - 1, length($0) ) }')/$(params.changeNumber)/$(params.patchSetNumber)"
+        echo $change_ref
+
+        cd "$(workspaces.output.path)"/jarvis
+
+        helm upgrade --install development-pipeline \
+          -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) \
+          ./development-pipeline \
+          --set "git_repo=$(params.repoRoot)/$(params.project)" \
+          --set "refspec=$change_ref"
+    - name: create-pipelinerun
+      image: {{ include "helpers.pod.container.image" ( dict "Global" $ "Application" "task_secrets" ) }}
+      script: |
+        #!/bin/bash
+
+        kubectl create \
+          -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) \
+          -f "$(workspaces.output.path)"/jarvis/development-pipeline/pipelinerun-validation.yaml
+
+            # Default wait timeout is 1000 seconds
+            end=$(date +%s)
+            timeout=${3:-3000}
+            end=$((end + timeout))
+
+            while true; do
+                pipelinerunstatus="$(kubectl get pipelinerun -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) $(kubectl get pipelinerun -n jarvis-$(params.changeNumber)-$(params.patchSetNumber) -o name | awk -F '/' "/development-pipeline/ { print \$NF; exit }") | tail -1 | awk '{ print $2 }')"
+                [ "${pipelinerunstatus}" == "True" ] && break
+                [ "${pipelinerunstatus}" == "False" ] && exit 1
+                sleep 5
+                now=$(date +%s)
+                if  [ $now -gt $end ] ; then
+                    echo "Pipelinerun failed to complete after $timeout seconds"
+                    echo
+                    kubectl get pipelinerun --namespace jarvis-$(params.changeNumber)-$(params.patchSetNumber) -o wide
+                    echo "Some pipelineruns are not complete"
+                    exit 1
+                fi
+                echo "kubectl get pipelinerun -n jarvis-$(params.changeNumber)-$(params.patchSetNumber)" | grep development-pipeline
+            done
 ...
 {{- end -}}
 {{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Task-createProjectAccess" ) }}
